In [5]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

In [6]:
df = pd.read_csv('E:/Machine_Learning/Datasets/Protein.csv',index_col=0)
df.head()

                RedMeat  WhiteMeat  Eggs  Milk  Fish  Cereals  Starch  Nuts  Fr&Veg
Country
Albania            10.1        1.4   0.5   8.9   0.2     42.3     0.6   5.5     1.7
Austria             8.9       14.0   4.3  19.9   2.1     28.0     3.6   1.3     4.3
Belgium            13.5        9.3   4.1  17.5   4.5     26.6     5.7   2.1     4.0
Bulgaria            7.8        6.0   1.6   8.3   1.2     56.7     1.1   3.7     4.2
Czechoslovakia      9.7       11.4   2.8  12.5   2.0     34.3     5.0   1.1     4.0

In [7]:
scaler = StandardScaler().set_output(transform='pandas')
scl_data = scaler.fit_transform(df)

In [8]:
scores = []
for k in range(2,15):
    km = KMeans(n_clusters=k)
    km.fit(scl_data)
    scores.append([k,silhouette_score(scl_data,km.labels_)])
df_scr = pd.DataFrame(scores,columns=['K','score'])
df_scr.sort_values(by= 'score',ascending=False)

     K     score
1    3  0.335169
0    2  0.327108
2    4  0.258341
3    5  0.246547
8   10  0.227256
6    8  0.191362
10  12  0.190520
7    9  0.185318
9   11  0.184297
12  14  0.173515
4    6  0.167535
5    7  0.151798
11  13  0.146729

## Q2 B

In [9]:
pc = PCA().set_output(transform='pandas')
pca_data = pc.fit_transform(scl_data)
pca_data.head()

                    pca0      pca1      pca2      pca3      pca4      pca5      pca6      pca7      pca8
Country
Albania         3.557238 -1.664102 -1.797551  0.234394  0.023733 -1.055592 -0.481470 -0.777255 -0.105382
Austria        -1.452006 -1.062702  1.365390  0.171564 -0.952695  0.222932 -0.184890  0.256178 -0.221930
Belgium        -1.655480  0.162784  0.221000  0.531464  0.770661 -0.295781 -0.199630  0.207504 -0.033855
Bulgaria        3.198708 -1.327895  0.154409  0.218606 -0.494741 -0.709921  0.474367  0.824911 -0.306046
Czechoslovakia -0.378104 -0.615096  1.220603 -0.473550  0.262120 -0.840063  0.321443 -0.012552 -0.152530

In [13]:
pc.explained_variance_ratio_*100

array([44.51597304, 18.16666052, 12.53243894, 10.60737739,  5.15375995,
        3.61256635,  3.01784816,  1.29213227,  1.10124338])

In [14]:
np.cumsum(pc.explained_variance_ratio_*100)

array([ 44.51597304,  62.68263357,  75.2150725 ,  85.82244989,
        90.97620984,  94.58877619,  97.60662435,  98.89875662,
       100.        ])

## 4 Principal components explain 85% of variance