In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis,QuadraticDiscriminantAnalysis
import os
os.chdir('E:/Machine_Learning/Cases/Image_Segmentation')

In [2]:
img = pd.read_csv('Image_Segmentation.csv')
img.head()

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
0,BRICKFACE,188,133,9,0.0,0.0,0.333333,0.266667,0.500000,0.077778,6.666666,8.333334,7.777778,3.888889,5.000000,3.333333,-8.333333,8.444445,0.538580,-0.924817
1,BRICKFACE,105,139,9,0.0,0.0,0.277778,0.107407,0.833333,0.522222,6.111111,7.555555,7.222222,3.555556,4.333334,3.333333,-7.666666,7.555555,0.532628,-0.965946
2,BRICKFACE,34,137,9,0.0,0.0,0.500000,0.166667,1.111111,0.474074,5.851852,7.777778,6.444445,3.333333,5.777778,1.777778,-7.555555,7.777778,0.573633,-0.744272
3,BRICKFACE,39,111,9,0.0,0.0,0.722222,0.374074,0.888889,0.429629,6.037037,7.000000,7.666666,3.444444,2.888889,4.888889,-7.777778,7.888889,0.562919,-1.175773
4,BRICKFACE,16,128,9,0.0,0.0,0.500000,0.077778,0.666667,0.311111,5.555555,6.888889,6.666666,3.111111,4.000000,3.333333,-7.333334,7.111111,0.561508,-0.985811

## LDA

In [4]:
X , y = img.drop('Class',axis=1) , img['Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)
lda = LinearDiscriminantAnalysis()
lda.fit(X_train,y_train)
y_pred = lda.predict(X_test)
accuracy_score(y_test,y_pred)

0.9206349206349206

## QDA

In [5]:
qda = QuadraticDiscriminantAnalysis()
qda.fit(X_train,y_train)
y_pred = qda.predict(X_test)
accuracy_score(y_test,y_pred)

LinAlgError: The covariance matrix of class BRICKFACE is not full rank. Increase the value of `reg_param` to reduce the collinearity.

### In this error => 
### in some of the matrix of (variance,covariance) one of the matrix have determinant as 0 
### so its inverse can't be calculated so the formula doesn't work .. so we use reg_param=  to fine tune the model 
### refer documentation of QDA for reg_param

In [6]:
qda = QuadraticDiscriminantAnalysis(reg_param=0.1)
qda.fit(X_train,y_train)
y_pred = qda.predict(X_test)
accuracy_score(y_test,y_pred)

0.873015873015873

# Satellite Image

In [7]:
os.chdir('E:/Machine_Learning/Cases/Satellite_Imaging')

In [11]:
satellite = pd.read_csv('Satellite.csv',sep=';')
satellite.head()

,x.1,x.2,x.3,x.4,x.5,x.6,x.7,x.8,x.9,x.10,...,x.28,x.29,x.30,x.31,x.32,x.33,x.34,x.35,x.36,classes
0,92,115,120,94,84,102,106,79,84,102,...,104,88,121,128,100,84,107,113,87,grey soil
1,84,102,106,79,84,102,102,83,80,102,...,100,84,107,113,87,84,99,104,79,grey soil
2,84,102,102,83,80,102,102,79,84,94,...,87,84,99,104,79,84,99,104,79,grey soil
3,80,102,102,79,84,94,102,79,80,94,...,79,84,99,104,79,84,103,104,79,grey soil
4,84,94,102,79,80,94,98,76,80,102,...,79,84,103,104,79,79,107,109,87,grey soil

In [13]:
X ,y = satellite.drop('classes',axis=1),satellite['classes']

# LDA

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)
lda = LinearDiscriminantAnalysis()
lda.fit(X_train,y_train)
y_pred = lda.predict(X_test)
accuracy_score(y_test,y_pred)

0.8410150181253236

## QDA

In [16]:
qda = QuadraticDiscriminantAnalysis()
qda.fit(X_train,y_train)
y_pred = qda.predict(X_test)
accuracy_score(y_test,y_pred)

0.8513723459347489

In [24]:
reg = np.linspace(0,1,10)
for r in reg:
    qda = QuadraticDiscriminantAnalysis(reg_param=r)
    qda.fit(X_train,y_train)
    y_pred = qda.predict(X_test)
    acc= accuracy_score(y_test,y_pred)
    print(r,' : ',acc)

0.0  :  0.8513723459347489
0.1111111111111111  :  0.8513723459347489
0.2222222222222222  :  0.8518902123252201
0.3333333333333333  :  0.8555152770585189
0.4444444444444444  :  0.8575867426204039
0.5555555555555556  :  0.8612118073537027
0.6666666666666666  :  0.8591403417918178
0.7777777777777777  :  0.8586224754013465
0.8888888888888888  :  0.8663904712584153
1.0  :  0.7819782496116002