In [5]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
import os
os.chdir('E:/Machine_Learning/Cases/student_performance')

In [6]:
df = pd.read_csv('student_dataset_10000_rows.csv')
df.head()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [7]:
X,y = df.drop('placement_status',axis=1),df['placement_status']

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)
scaler = StandardScaler()

In [18]:
ks = np.arange(1,16)
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    pipe1 = Pipeline([('SCL',scaler),('KNN',knn)])
    pipe1.fit(X_train,y_train)
    y_pred = pipe1.predict(X_test)
    scores.append([k,accuracy_score(y_test,y_pred)])

df_scores = pd.DataFrame(scores,columns=['K','Accuracy'])
df_scores.sort_values(by=['Accuracy'],ascending=False)

     K  Accuracy
14  15  0.973000
12  13  0.972333
13  14  0.971667
7    8  0.971000
11  12  0.969667
8    9  0.969333
6    7  0.968667
10  11  0.968333
9   10  0.968000
5    6  0.967333
4    5  0.965333
2    3  0.962000
3    4  0.960000
0    1  0.952000
1    2  0.951000

## GaussianNB

In [20]:
gnb = GaussianNB()
pipe2 = Pipeline([('SCL',scaler),('KNN',knn)])
pipe2.fit(X_train,y_train)
y_pred = pipe2.predict(X_test)
accuracy_score(y_test,y_pred)

0.973