# BaggingClassifier

In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from tqdm import tqdm
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
import os
os.chdir('E:/Machine_Learning/Cases/Wisconsin/')

In [22]:
wisc = pd.read_csv("BreastCancer.csv",index_col=0)
wisc.head()

        Clump  UniCell_Size  Uni_CellShape  MargAdh  SEpith  BareN  BChromatin  NoemN  Mitoses      Class
Code
61634       5             4              3        1       2      2           2      3        1     Benign
63375       9             1              2        6       4     10           7      7        2  Malignant
76389      10             4              7        2       2      8           6      1        1  Malignant
95719       6            10             10       10       8     10           7     10        7  Malignant
128059      1             1              1        1       2      5           5      1        1     Benign

In [23]:
X,y = wisc.drop('Class',axis = 1),wisc['Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=26,test_size=0.3,stratify=y)

lr  = LogisticRegression()
bag = BaggingClassifier(estimator=lr,n_estimators=15,random_state=26)

bag.fit(X_train,y_train)
y_pred = bag.predict(X_test)
accuracy_score(y_test,y_pred)

0.9571428571428572

## Trying different estimators

In [24]:
dtc = DecisionTreeClassifier()
knn = KNeighborsClassifier(n_neighbors=5)
lr = LogisticRegression()
est = [lr,knn,dtc]
n_samples = [10,25,50]
scores = []
for e in est:
    for n in n_samples:
        bag = BaggingClassifier(estimator=e,n_estimators=n,random_state=26)
        bag.fit(X_train,y_train)
        y_pred = bag.predict(X_test)
        scores.append([e,n,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores,columns=['Estimator','n estimator','score'])
df_scores.sort_values('score',ascending=False)

                  Estimator  n estimator     score
6  DecisionTreeClassifier()           10  0.966667
5    KNeighborsClassifier()           50  0.966667
7  DecisionTreeClassifier()           25  0.966667
3    KNeighborsClassifier()           10  0.961905
2      LogisticRegression()           50  0.961905
8  DecisionTreeClassifier()           50  0.961905
4    KNeighborsClassifier()           25  0.961905
1      LogisticRegression()           25  0.957143
0      LogisticRegression()           10  0.952381

# BaggingRegressor

In [30]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.metrics import r2_score
import os
os.chdir('E:/Machine_Learning/Cases/Concrete_Strength/')

In [31]:
df = pd.read_csv('Concrete_Data.csv')
df.head()

   Cement  Blast  Fly  Water  Superplasticizer  Coarse   Fine  Age  Strength
0   540.0    0.0  0.0  162.0               2.5  1040.0  676.0   28     79.99
1   540.0    0.0  0.0  162.0               2.5  1055.0  676.0   28     61.89
2   332.5  142.5  0.0  228.0               0.0   932.0  594.0  270     40.27
3   332.5  142.5  0.0  228.0               0.0   932.0  594.0  365     41.05
4   198.6  132.4  0.0  192.0               0.0   978.4  825.5  360     44.30

In [32]:
X,y=df.drop('Strength',axis=1),df['Strength']
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.3)
dtr = DecisionTreeRegressor(random_state=26)
bagreg = BaggingRegressor(estimator=dtr,n_estimators=15,random_state=26)
bagreg.fit(X_train,y_train)
y_pred = bagreg.predict(X_test)
r2_score(y_test,y_pred)

0.8806624124743665

In [33]:
lr = LinearRegression()
ridge = Ridge()
lasso = Lasso()
dtr = DecisionTreeRegressor(random_state=26)
estimators = [lr,ridge,lasso,dtr]
sample = [10,25,50]
scores=[]
for e in estimators:
    for s in sample:
        bag = BaggingRegressor(estimator=e,n_estimators=s,random_state=26)
        bag.fit(X_train,y_train)
        y_pred=bag.predict(X_test)
        scores.append([e,s,r2_score(y_test,y_pred)])

df_s =pd.DataFrame(scores,columns=['Estimator','n','r2'])
df_s.sort_values(by= 'r2',ascending=False)

                                 Estimator   n        r2
11  DecisionTreeRegressor(random_state=26)  50  0.881771
10  DecisionTreeRegressor(random_state=26)  25  0.880547
9   DecisionTreeRegressor(random_state=26)  10  0.870059
7                                  Lasso()  25  0.597140
8                                  Lasso()  50  0.595977
6                                  Lasso()  10  0.595806
4                                  Ridge()  25  0.595205
1                       LinearRegression()  25  0.595204
5                                  Ridge()  50  0.594057
2                       LinearRegression()  50  0.594056
3                                  Ridge()  10  0.593486
0                       LinearRegression()  10  0.593484