In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve,roc_auc_score,RocCurveDisplay
from tqdm import tqdm
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay,classification_report
import os 
os.chdir('E:/Machine_Learning/Cases/Kyphosis/')

In [8]:
df = pd.read_csv("Kyphosis.csv")
df

   Kyphosis  Age  Number  Start
0    absent   71       3      5
1    absent  158       3     14
2   present  128       4      5
3    absent    2       5      1
4    absent    1       4     15
..      ...  ...     ...    ...
76  present  157       3     13
77   absent   26       7     13
78   absent  120       2     13
79  present   42       7      6
80   absent   36       4     13

[81 rows x 4 columns]

In [11]:
X,y = df.drop('Kyphosis',axis=1),df['Kyphosis']
le = LabelEncoder()
le_y = le.fit_transform(y)
X_train,X_test,y_train,y_test = train_test_split(X,le_y,test_size=0.3,random_state=26,stratify=le_y)

In [14]:
gbc = GradientBoostingClassifier(random_state=26)
gbc.fit(X_train,y_train)
y_pred = gbc.predict(X_test)
roc_auc_score(y_test,y_pred)

0.45

In [21]:
gbc.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0])

In [20]:
gbc.predict_proba(X_test)

array([[9.90198405e-01, 9.80159509e-03],
       [9.94870218e-01, 5.12978206e-03],
       [9.99634601e-01, 3.65399231e-04],
       [9.99937391e-01, 6.26093811e-05],
       [9.69305076e-01, 3.06949244e-02],
       [9.99747678e-01, 2.52322362e-04],
       [9.99937391e-01, 6.26093811e-05],
       [9.98099406e-01, 1.90059361e-03],
       [9.99430282e-01, 5.69717995e-04],
       [4.74818489e-01, 5.25181511e-01],
       [9.95574069e-01, 4.42593120e-03],
       [9.98584554e-01, 1.41544561e-03],
       [9.99251679e-01, 7.48321086e-04],
       [9.91940841e-01, 8.05915922e-03],
       [9.99609395e-01, 3.90604918e-04],
       [9.76052239e-01, 2.39477614e-02],
       [9.99024693e-01, 9.75307300e-04],
       [1.67192456e-01, 8.32807544e-01],
       [9.99937391e-01, 6.26093811e-05],
       [9.92054516e-01, 7.94548413e-03],
       [9.97043144e-01, 2.95685582e-03],
       [9.99430282e-01, 5.69717995e-04],
       [9.99937391e-01, 6.26093811e-05],
       [9.99769454e-01, 2.30546324e-04],
       [9.90265091e-01, 9.73490861e-03]])

In [17]:
gbc = GradientBoostingClassifier(random_state=26)
gbc.fit(X_train,y_train)
y_pred_prob = gbc.predict_proba(X_test)
roc_auc_score(y_test,y_pred_prob[:,1])

0.45999999999999996

In [22]:
learn_rates = np.linspace(0.01,0.9,10)
max_depths = [None,2,3,4]
n_estimators = [25,50,100]
scores = []
for l in tqdm(learn_rates):
    for m in max_depths:
        for n in n_estimators:
            gbm = GradientBoostingClassifier(random_state=26,learning_rate=l,max_depth=m,n_estimators=n)
            gbm.fit(X_train,y_train)
            y_pred = gbm.predict_proba(X_test)
            scores.append([l,m,n,roc_auc_score(y_test,y_pred_prob[:,1])])
df_scores = pd.DataFrame(scores,columns=['Learning_rate','Max_depth','n_estimators','roc_auc_score'])
df_scores.sort_values(by='roc_auc_score',ascending=False)

100%|██████████| 10/10 [00:06<00:00,  1.54it/s]

     Learning_rate  Max_depth  n_estimators  roc_auc_score
0             0.01        NaN            25           0.46
1             0.01        NaN            50           0.46
2             0.01        NaN           100           0.46
3             0.01        2.0            25           0.46
4             0.01        2.0            50           0.46
..             ...        ...           ...            ...
115           0.90        3.0            50           0.46
116           0.90        3.0           100           0.46
117           0.90        4.0            25           0.46
118           0.90        4.0            50           0.46
119           0.90        4.0           100           0.46

[120 rows x 4 columns]