In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay,classification_report
import matplotlib.pyplot as plt
import os
os.chdir('E:/Machine_Learning/Cases/Wisconsin/')

In [20]:
wisc = pd.read_csv("BreastCancer.csv",index_col=0)
wisc.head()

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
61634,5,4,3,1,2,2,2,3,1,Benign
63375,9,1,2,6,4,10,7,7,2,Malignant
76389,10,4,7,2,2,8,6,1,1,Malignant
95719,6,10,10,10,8,10,7,10,7,Malignant
128059,1,1,1,1,2,5,5,1,1,Benign

In [21]:
X,y = wisc.drop('Class',axis = 1),wisc['Class']
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)
rf = RandomForestClassifier(n_estimators=25,max_features=3)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.9666666666666667

In [22]:
m_feat=[2,3,4,5]
samples = [25,50,100]
scores = []
for m in m_feat:
    for s in samples:
        rf = RandomForestClassifier(n_estimators=s,max_features=m,random_state=26)
        rf.fit(X_train,y_train)
        y_pred = rf.predict(X_test)
        scores.append([s,m,precision_score(y_test,y_pred,pos_label='Malignant')])
df_s =pd.DataFrame(scores,columns=['n','Max_features','precision'])
df_s.sort_values(by= 'precision',ascending=False)

      n  Max_features  precision
0    25             2   0.922078
1    50             2   0.922078
2   100             2   0.922078
4    50             3   0.922078
11  100             5   0.922078
5   100             3   0.922078
7    50             4   0.922078
8   100             4   0.922078
10   50             5   0.922078
3    25             3   0.921053
6    25             4   0.898734
9    25             5   0.897436

In [23]:
m_feat=[2,3,4,5]
samples = [25,50,100]
scores = []
for m in m_feat:
    for s in samples:
        rf = RandomForestClassifier(n_estimators=s,max_features=m,random_state=26)
        rf.fit(X_train,y_train)
        y_pred = rf.predict(X_test)
        scores.append([s,m,recall_score(y_test,y_pred,pos_label='Malignant'),
                       precision_score(y_test,y_pred,pos_label='Malignant'),
                       f1_score(y_test,y_pred,pos_label='Malignant')
                      ])
df_s =pd.DataFrame(scores,columns=['n','Max_features','recall','precision','f1'])
df_s

      n  Max_features    recall  precision        f1
0    25             2  0.986111   0.922078  0.953020
1    50             2  0.986111   0.922078  0.953020
2   100             2  0.986111   0.922078  0.953020
3    25             3  0.972222   0.921053  0.945946
4    50             3  0.986111   0.922078  0.953020
5   100             3  0.986111   0.922078  0.953020
6    25             4  0.986111   0.898734  0.940397
7    50             4  0.986111   0.922078  0.953020
8   100             4  0.986111   0.922078  0.953020
9    25             5  0.972222   0.897436  0.933333
10   50             5  0.986111   0.922078  0.953020
11  100             5  0.986111   0.922078  0.953020

In [24]:
rf = RandomForestClassifier(n_estimators=25,max_features=3)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.9476190476190476

In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      Benign       0.98      0.93      0.96       138
   Malignant       0.89      0.97      0.93        72

    accuracy                           0.95       210
   macro avg       0.94      0.95      0.94       210
weighted avg       0.95      0.95      0.95       210

## Vehicle dataset

In [26]:
os.chdir('E:/Machine_Learning/Cases/Vehicle Silhouettes/')
vehicle= pd.read_csv("Vehicle.csv")
vehicle.head()

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus

In [27]:
X,y = vehicle.drop('Class',axis=1),vehicle['Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [28]:
rf = RandomForestClassifier(n_estimators=25,max_features=3)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7401574803149606

In [32]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         bus       0.93      1.00      0.96        65
        opel       0.56      0.55      0.56        64
        saab       0.57      0.49      0.53        65
         van       0.86      0.95      0.90        60

    accuracy                           0.74       254
   macro avg       0.73      0.75      0.74       254
weighted avg       0.73      0.74      0.74       254

In [31]:
m_feat=[2,3,4,5]
samples = [25,50,100]
scores = []
for m in m_feat:
    for s in samples:
        rf = RandomForestClassifier(n_estimators=s,max_features=m,random_state=26)
        rf.fit(X_train,y_train)
        y_pred = rf.predict(X_test)
        scores.append([s,m,recall_score(y_test,y_pred,pos_label='van',average='weighted'),
                       precision_score(y_test,y_pred,pos_label='van',average='weighted'),
                       f1_score(y_test,y_pred,pos_label='van',average='weighted')
                      ])
df_s =pd.DataFrame(scores,columns=['n','Max_features','recall','precision','f1'])
df_s

C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1929: UserWarning: Note that pos_label (set to 'van') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(

      n  Max_features    recall  precision        f1
0    25             2  0.740157   0.723552  0.729223
1    50             2  0.759843   0.746464  0.751071
2   100             2  0.755906   0.742998  0.747911
3    25             3  0.763780   0.753190  0.756671
4    50             3  0.755906   0.742504  0.746110
5   100             3  0.751969   0.739141  0.744039
6    25             4  0.736220   0.723157  0.728312
7    50             4  0.771654   0.760244  0.764237
8   100             4  0.755906   0.743400  0.748211
9    25             5  0.732283   0.718520  0.723829
10   50             5  0.751969   0.736606  0.741187
11  100             5  0.744094   0.730107  0.735488