In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import GridSearchCV,StratifiedKFold
from sklearn.metrics import roc_auc_score , log_loss

from sklearn.preprocessing import StandardScaler,MinMaxScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
import os
import warnings
from sklearn.exceptions import ConvergenceWarning
warnings.filterwarnings("ignore",category = ConvergenceWarning)

In [2]:
# !pip install ucimlrepo

In [3]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
cirrhosis_patient_survival_prediction = fetch_ucirepo(id=878) 
  
# data (as pandas dataframes) 
X = cirrhosis_patient_survival_prediction.data.features 
y = cirrhosis_patient_survival_prediction.data.targets 
  

# print(cirrhosis_patient_survival_prediction.metadata) 
  

# print(cirrhosis_patient_survival_prediction.variables)

In [4]:
y

    Status
0        D
1        C
2        D
3        D
4       CL
..     ...
413      D
414      C
415      C
416      C
417      C

[418 rows x 1 columns]

# We have to look at every column

In [5]:
X.columns

Index(['Drug', 'Age', 'Sex', 'Ascites', 'Hepatomegaly', 'Spiders', 'Edema',
       'Bilirubin', 'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos', 'SGOT',
       'Tryglicerides', 'Platelets', 'Prothrombin', 'Stage'],
      dtype='str')

### Because Our data contains Too much NaNN values not nan values so we have replaved that NaNN to nan

In [6]:
X = X.replace(['NaNN','nan','nann','nann'], np.nan)

In [7]:
X.dtypes

Drug                 str
Age                int64
Sex                  str
Ascites              str
Hepatomegaly         str
Spiders              str
Edema                str
Bilirubin        float64
Cholesterol          str
Albumin          float64
Copper               str
Alk_Phos         float64
SGOT             float64
Tryglicerides        str
Platelets            str
Prothrombin      float64
Stage            float64
dtype: object

### Some columns odes contain numerical values but it is in string format in df so we convert it into float

In [8]:
X['Cholesterol'].astype(float)
X['Copper'].astype(float)
X['Tryglicerides'].astype(float)
X['Platelets'].astype(float)

0      190.0
1      221.0
2      151.0
3      183.0
4      136.0
       ...
413    174.0
414    180.0
415    143.0
416    269.0
417    350.0
Name: Platelets, Length: 418, dtype: float64

In [9]:
X

,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261,2.60,156,1718.0,137.95,172,190,12.2,4.0
1,D-penicillamine,20617,F,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6,3.0
2,D-penicillamine,25594,M,N,N,N,S,1.4,176,3.48,210,516.0,96.10,55,151,12.0,4.0
3,D-penicillamine,19994,F,N,Y,Y,S,1.8,244,2.54,64,6121.8,60.63,92,183,10.3,4.0
4,Placebo,13918,F,N,Y,Y,N,3.4,279,3.53,143,671.0,113.15,72,136,10.9,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,NaN,24472,F,NaN,NaN,NaN,N,1.2,NaN,2.96,NaN,NaN,NaN,NaN,174,10.9,3.0
414,NaN,14245,F,NaN,NaN,NaN,N,0.9,NaN,3.83,NaN,NaN,NaN,NaN,180,11.2,4.0
415,NaN,20819,F,NaN,NaN,NaN,N,1.6,NaN,3.42,NaN,NaN,NaN,NaN,143,9.9,3.0
416,NaN,21185,F,NaN,NaN,NaN,N,0.8,NaN,3.75,NaN,NaN,NaN,NaN,269,10.4,3.0
417,NaN,19358,F,NaN,NaN,NaN,N,0.7,NaN,3.29,NaN,NaN,NaN,NaN,350,10.6,4.0

In [10]:
num_imputer = SimpleImputer(strategy='mean').set_output(transform='pandas')
cat_imputer = SimpleImputer(strategy='constant',fill_value='Unknown').set_output(transform='pandas')

std_scaler = StandardScaler()

mm_scaler = MinMaxScaler()
knn = KNeighborsClassifier()
kfold = StratifiedKFold(n_splits=5,shuffle=True,random_state=26)
ct_impute = make_column_transformer((cat_imputer,make_column_selector(dtype_include=object)),
                                (num_imputer,make_column_selector(dtype_include=['int64','float64'])),
                                verbose_feature_names_out=False).set_output(transform='pandas')

In [11]:
ohe = OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')

ct_ohe = make_column_transformer((ohe,make_column_selector(dtype_include='object')),
                                ('passthrough',make_column_selector(dtype_include=['int64','float64'])),
                                verbose_feature_names_out=False).set_output(transform='pandas')

pipe = Pipeline([('IMP',ct_impute),('OHE',ct_ohe),('SCL',std_scaler),('KNN',knn)])
pipe

Pipeline(steps=[('IMP',
                 ColumnTransformer(transformers=[('simpleimputer-1',
                                                  SimpleImputer(fill_value='Unknown',
                                                                strategy='constant'),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000002822CEBECF0>),
                                                 ('simpleimputer-2',
                                                  SimpleImputer(),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000002822CEE0CD0>)],
                                   verbose_feat...
                 ColumnTransformer(transformers=[('onehotencoder',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000002822CEE0B90>),
                                                 ('passthrough', 'passthrough',
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000002822CEC1350>)],
                                   verbose_feature_names_out=False)),
                ('SCL', StandardScaler()), ('KNN', KNeighborsClassifier())])

In [12]:
params = {'IMP__simpleimputer-1__strategy':['constant','most_frequent'],
          'IMP__simpleimputer-2__strategy':['mean','median'],
         'SCL':[std_scaler,mm_scaler,None],
         'KNN__n_neighbors':np.arange(1,11)
         }

In [13]:
gcv = GridSearchCV(pipe,param_grid=params,cv = kfold,n_jobs = -1,scoring='neg_log_loss')
gcv.fit(X,y['Status'])
print('Best Param : ',gcv.best_params_)
print('Best Score : ',gcv.best_score_)

Best Param :  {'IMP__simpleimputer-1__strategy': 'constant', 'IMP__simpleimputer-2__strategy': 'mean', 'KNN__n_neighbors': np.int64(1), 'SCL': StandardScaler()}
Best Score :  nan

C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\model_selection\_search.py:1237: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan]
  warnings.warn(

^C
Collecting ISLP
  Downloading islp-0.4.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: numpy>=1.7.1 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ISLP) (2.5.3)
Requirement already satisfied: scipy>=0.9 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ISLP) (1.18.1)
Requirement already satisfied: pandas>=1.5 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ISLP) (3.0.5)
Collecting lxml (from ISLP)
  Using cached lxml-6.1.3-cp314-cp314-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: scikit-learn>=1.2 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ISLP) (1.9.1)
Requirement already satisfied: joblib in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ISLP) (1.6.0)
Requirement already satisfied: statsmodels>=0.13 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ISLP) (0.15.0)
Collecting lifelines (from ISLP)
  Downloading lifelines-0.30.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pygam (from ISLP)
  Downloading pygam-0.12.0-py3-none-any.whl.metadata (9.8 kB)
Collecting torch (from ISLP)
  Downloading torch-2.14.1-cp314-cp314-win_amd64.whl.metadata (38 kB)
Collecting pytorch_lightning (from ISLP)
  Downloading pytorch_lightning-2.6.6-py3-none-any.whl.metadata (21 kB)
Collecting torchmetrics (from ISLP)
  Downloading torchmetrics-1.9.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.5->ISLP) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.5->ISLP) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5->ISLP) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn>=1.2->ISLP) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn>=1.2->ISLP) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from joblib->ISLP) (3.1.2)
Requirement already satisfied: patsy>=0.5.6 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from statsmodels>=0.13->ISLP) (1.0.3)
Requirement already satisfied: packaging>=21.3 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from statsmodels>=0.13->ISLP) (26.3)
Requirement already satisfied: formulaic>=1.1.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from statsmodels>=0.13->ISLP) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from formulaic>=1.1.0->statsmodels>=0.13->ISLP) (2.0.1)
Requirement already satisfied: typing-extensions>=4.2.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from formulaic>=1.1.0->statsmodels>=0.13->ISLP) (4.16.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from formulaic>=1.1.0->statsmodels>=0.13->ISLP) (2.5.0)
Collecting pandas>=1.5 (from ISLP)
  Downloading pandas-2.3.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: matplotlib>=3.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from lifelines->ISLP) (3.11.2)
Collecting autograd>=1.5 (from lifelines->ISLP)
  Downloading autograd-1.9.1-py3-none-any.whl.metadata (6.1 kB)
Collecting autograd-gamma>=0.3 (from lifelines->ISLP)
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting pytz>=2020.1 (from pandas>=1.5->ISLP)
  Downloading pytz-2026.5-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.0->lifelines->ISLP) (1.4.0)
Requirement already satisfied: cycler>=0.10 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.0->lifelines->ISLP) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.0->lifelines->ISLP) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.0->lifelines->ISLP) (1.5.1)
Requirement already satisfied: pillow>=9 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.0->lifelines->ISLP) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.0->lifelines->ISLP) (3.3.2)
Collecting progressbar2<5,>=4.2.0 (from pygam->ISLP)
  Downloading progressbar2-4.6.0-py3-none-any.whl.metadata (10 kB)
Collecting scipy>=0.9 (from ISLP)
  Downloading scipy-1.16.3-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting python-utils>=3.8.1 (from progressbar2<5,>=4.2.0->pygam->ISLP)
  Downloading python_utils-4.1.3-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tqdm>=4.57.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pytorch_lightning->ISLP) (4.70.1)
Requirement already satisfied: PyYAML>5.4 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pytorch_lightning->ISLP) (6.0.3)
Collecting fsspec>=2022.5.0 (from fsspec[http]>=2022.5.0->pytorch_lightning->ISLP)
  Downloading fsspec-2026.9.0-py3-none-any.whl.metadata (10 kB)
Collecting lightning-utilities>=0.10.0 (from pytorch_lightning->ISLP)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]>=2022.5.0->pytorch_lightning->ISLP)
  Downloading aiohttp-3.14.5-cp314-cp314-win_amd64.whl.metadata (8.5 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->ISLP)
  Using cached aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->ISLP)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->ISLP) (26.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->ISLP)
  Using cached frozenlist-1.8.0-cp314-cp314-win_amd64.whl.metadata (21 kB)
Collecting multidict<8.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->ISLP)
  Downloading multidict-7.1.0-cp314-cp314-win_amd64.whl.metadata (6.4 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->ISLP)
  Using cached propcache-0.5.4-cp314-cp314-win_amd64.whl.metadata (25 kB)
Collecting yarl<2.0,>=1.25.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->ISLP)
  Using cached yarl-1.25.1-cp314-cp314-win_amd64.whl.metadata (115 kB)
Requirement already satisfied: idna>=2.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yarl<2.0,>=1.25.1->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->ISLP) (3.19)
Collecting filelock (from torch->ISLP)
  Downloading filelock-4.2.4-py3-none-any.whl.metadata (2.0 kB)
Collecting setuptools>=77.0.3 (from torch->ISLP)
  Using cached setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch->ISLP)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch->ISLP)
  Downloading networkx-3.7-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: jinja2 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch->ISLP) (3.1.6)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch->ISLP)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: colorama in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tqdm>=4.57.0->pytorch_lightning->ISLP) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jinja2->torch->ISLP) (3.0.3)
Downloading islp-0.4.1-py3-none-any.whl (16.6 MB)
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
    --------------------------------------- 0.3/16.6 MB ? eta -:--:--
    --------------------------------------- 0.3/16.6 MB ? eta -:--:--
    --------------------------------------- 0.3/16.6 MB ? eta -:--:--
    --------------------------------------- 0.3/16.6 MB ? eta -:--:--
    --------------------------------------- 0.3/16.6 MB ? eta -:--:--
    --------------------------------------- 0.3/16.6 MB ? eta -:--:--
    --------------------------------------- 0.3/16.6 MB ? eta -:--:--
    --------------------------------------- 0.3/16.6 MB ? eta -:--:--
    --------------------------------------- 0.3/16.6 MB ? eta -:--:--
    --------------------------------------- 0.3/16.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/16.6 MB 123.7 kB/s eta 0:02:10
   - -------------------------------------- 0.5/16.6 MB 123.7 kB/s eta 0:02:10
   - -------------------------------------- 0.5/16.6 MB 123.7 kB/s eta 0:02:10
   - -------------------------------------- 0.5/16.6 MB 123.7 kB/s eta 0:02:10
   - -------------------------------------- 0.5/16.6 MB 123.7 kB/s eta 0:02:10
   - -------------------------------------- 0.5/16.6 MB 123.7 kB/s eta 0:02:10
   - -------------------------------------- 0.5/16.6 MB 123.7 kB/s eta 0:02:10
   - -------------------------------------- 0.5/16.6 MB 123.7 kB/s eta 0:02:10
   - -------------------------------------- 0.5/16.6 MB 123.7 kB/s eta 0:02:10
   - -------------------------------------- 0.8/16.6 MB 129.7 kB/s eta 0:02:02
   - -------------------------------------- 0.8/16.6 MB 129.7 kB/s eta 0:02:02
   - -------------------------------------- 0.8/16.6 MB 129.7 kB/s eta 0:02:02
   - -------------------------------------- 0.8/16.6 MB 129.7 kB/s eta 0:02:02
   - -------------------------------------- 0.8/16.6 MB 129.7 kB/s eta 0:02:02
   - -------------------------------------- 0.8/16.6 MB 129.7 kB/s eta 0:02:02
   - -------------------------------------- 0.8/16.6 MB 129.7 kB/s eta 0:02:02
   - -------------------------------------- 0.8/16.6 MB 129.7 kB/s eta 0:02:02
   - -------------------------------------- 0.8/16.6 MB 129.7 kB/s eta 0:02:02
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   -- ------------------------------------- 1.0/16.6 MB 131.6 kB/s eta 0:01:59
   --- ------------------------------------ 1.3/16.6 MB 112.4 kB/s eta 0:02:16
   --- ------------------------------------ 1.3/16.6 MB 112.4 kB/s eta 0:02:16
   --- ------------------------------------ 1.3/16.6 MB 112.4 kB/s eta 0:02:16
   --- ------------------------------------ 1.3/16.6 MB 112.4 kB/s eta 0:02:16
   --- ------------------------------------ 1.3/16.6 MB 112.4 kB/s eta 0:02:16
   --- ------------------------------------ 1.3/16.6 MB 112.4 kB/s eta 0:02:16
   --- ------------------------------------ 1.3/16.6 MB 112.4 kB/s eta 0:02:16
   --- ------------------------------------ 1.6/16.6 MB 121.1 kB/s eta 0:02:04
   --- ------------------------------------ 1.6/16.6 MB 121.1 kB/s eta 0:02:04
   --- ------------------------------------ 1.6/16.6 MB 121.1 kB/s eta 0:02:04
   --- ------------------------------------ 1.6/16.6 MB 121.1 kB/s eta 0:02:04
   --- ------------------------------------ 1.6/16.6 MB 121.1 kB/s eta 0:02:04
   --- ------------------------------------ 1.6/16.6 MB 121.1 kB/s eta 0:02:04
   --- ------------------------------------ 1.6/16.6 MB 121.1 kB/s eta 0:02:04
   --- ------------------------------------ 1.6/16.6 MB 121.1 kB/s eta 0:02:04
   --- ------------------------------------ 1.6/16.6 MB 121.1 kB/s eta 0:02:04
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ---- ----------------------------------- 1.8/16.6 MB 122.4 kB/s eta 0:02:01
   ----- ---------------------------------- 2.1/16.6 MB 119.5 kB/s eta 0:02:02
   ----- ---------------------------------- 2.1/16.6 MB 119.5 kB/s eta 0:02:02
   ----- ---------------------------------- 2.1/16.6 MB 119.5 kB/s eta 0:02:02
   ----- ---------------------------------- 2.1/16.6 MB 119.5 kB/s eta 0:02:02
   ----- ---------------------------------- 2.1/16.6 MB 119.5 kB/s eta 0:02:02
   ----- ---------------------------------- 2.1/16.6 MB 119.5 kB/s eta 0:02:02
   ----- ---------------------------------- 2.1/16.6 MB 119.5 kB/s eta 0:02:02
   ----- ---------------------------------- 2.1/16.6 MB 119.5 kB/s eta 0:02:02
   ----- ---------------------------------- 2.1/16.6 MB 119.5 kB/s eta 0:02:02
   ----- ---------------------------------- 2.1/16.6 MB 119.5 kB/s eta 0:02:02
   ----- ---------------------------------- 2.1/16.6 MB 119.5 kB/s eta 0:02:02
   ----- ---------------------------------- 2.4/16.6 MB 117.7 kB/s eta 0:02:01
   ----- ---------------------------------- 2.4/16.6 MB 117.7 kB/s eta 0:02:01
   ----- ---------------------------------- 2.4/16.6 MB 117.7 kB/s eta 0:02:01
   ----- ---------------------------------- 2.4/16.6 MB 117.7 kB/s eta 0:02:01
   ----- ---------------------------------- 2.4/16.6 MB 117.7 kB/s eta 0:02:01
   ----- ---------------------------------- 2.4/16.6 MB 117.7 kB/s eta 0:02:01
   ----- ---------------------------------- 2.4/16.6 MB 117.7 kB/s eta 0:02:01
   ----- ---------------------------------- 2.4/16.6 MB 117.7 kB/s eta 0:02:01
   ----- ---------------------------------- 2.4/16.6 MB 117.7 kB/s eta 0:02:01
   ----- ---------------------------------- 2.4/16.6 MB 117.7 kB/s eta 0:02:01
   ------ --------------------------------- 2.6/16.6 MB 119.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.6/16.6 MB 119.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.6/16.6 MB 119.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.6/16.6 MB 119.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.6/16.6 MB 119.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.6/16.6 MB 119.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.6/16.6 MB 119.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.6/16.6 MB 119.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.6/16.6 MB 119.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.6/16.6 MB 119.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.6/16.6 MB 119.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.9/16.6 MB 119.2 kB/s eta 0:01:55
   ------ --------------------------------- 2.9/16.6 MB 119.2 kB/s eta 0:01:55
   ------ --------------------------------- 2.9/16.6 MB 119.2 kB/s eta 0:01:55
   ------ --------------------------------- 2.9/16.6 MB 119.2 kB/s eta 0:01:55
   ------ --------------------------------- 2.9/16.6 MB 119.2 kB/s eta 0:01:55
   ------ --------------------------------- 2.9/16.6 MB 119.2 kB/s eta 0:01:55
   ------ --------------------------------- 2.9/16.6 MB 119.2 kB/s eta 0:01:55

WARNING: Ignoring invalid distribution ~andas (C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages)
  WARNING: The script isympy.exe is installed in 'C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts torchfrtrace.exe and torchrun.exe are installed in 'C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script progressbar.exe is installed in 'C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.