In [1]:
import os 
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
os.chdir("E:/Machine_Learning/Datasets/")

In [4]:
df = pd.read_csv('milk.csv',index_col='Animal')
df.head()

           water  protein  fat  lactose   ash
Animal
HORSE       90.1      2.6  1.0      6.9  0.35
ORANGUTAN   88.5      1.4  3.5      6.0  0.24
MONKEY      88.4      2.2  2.7      6.4  0.18
DONKEY      90.3      1.7  1.4      6.2  0.40
HIPPO       90.4      0.6  4.5      4.4  0.10

In [7]:
scaler = StandardScaler().set_output(transform = 'pandas')
scl_milk = scaler.fit_transform(df)
scl_milk.head()

              water   protein       fat   lactose       ash
Animal
HORSE      0.948806 -1.009291 -0.903208  1.542217 -1.037554
ORANGUTAN  0.821407 -1.344603 -0.660619  1.040773 -1.259945
MONKEY     0.813445 -1.121062 -0.738247  1.263637 -1.381249
DONKEY     0.964731 -1.260775 -0.864394  1.152205 -0.936467
HIPPO      0.972694 -1.568145 -0.563583  0.149319 -1.542988

In [24]:
prcomp = PCA().set_output(transform='pandas')
pca_data = prcomp.fit_transform(scl_milk)
pca_data.head()

               pca0      pca1      pca2      pca3      pca4
Animal
HORSE      2.435175 -0.231478  0.330150  0.307664  0.048184
ORANGUTAN  2.258736 -0.693148  0.029035 -0.081057 -0.000532
MONKEY     2.335861 -0.663328  0.101257  0.247997  0.010109
DONKEY     2.318677 -0.273815  0.109881 -0.092873 -0.006769
HIPPO      2.060294 -1.019199 -0.762436 -0.510091  0.029382

In [10]:
df.shape,pca_data.shape

((25, 5), (25, 5))

In [11]:
pca_data.var()

pca0    4.040412
pca1    0.924372
pca2    0.134291
pca3    0.102689
pca4    0.006570
dtype: float64

In [13]:
sigma = scl_milk.cov()
values, vectors = np.linalg.eig(sigma)
print('Eigen Values : ' , values)

Eigen Values :  [4.0404117 +0.j 0.92437238+0.j 0.00656977+0.j 0.13429088+0.j
 0.1026886 +0.j]

In [25]:
print('Eigen Values : ' , vectors)

Eigen Values :  [[-0.47294379+0.j  0.35285509+0.j -0.70967042+0.j  0.36921298+0.j
   0.10893632+0.j]
 [ 0.46657047+0.j  0.32094099+0.j -0.1930657 +0.j  0.15196177+0.j
  -0.78672876+0.j]
 [ 0.44868269+0.j -0.47603724+0.j -0.66831106+0.j -0.30699163+0.j
   0.17660367+0.j]
 [-0.48289116+0.j  0.05951482+0.j -0.11159049+0.j -0.77642589+0.j
  -0.38468756+0.j]
 [ 0.35232959+0.j  0.73643513+0.j  0.00118661+0.j -0.378825  +0.j
   0.43590982+0.j]]

In [17]:
prcomp.explained_variance_

array([4.0404117 , 0.92437238, 0.13429088, 0.1026886 , 0.00656977])

-----

In [15]:
total_variation = pca_data.var().sum()
total_variation

np.float64(5.208333333333338)

In [16]:
pca_data.var()/total_variation

pca0    0.775759
pca1    0.177479
pca2    0.025784
pca3    0.019716
pca4    0.001261
dtype: float64

In [18]:
prcomp.explained_variance_ratio_

array([0.77575905, 0.1774795 , 0.02578385, 0.01971621, 0.0012614 ])

In [19]:
prcomp.explained_variance_ratio_*100

array([77.57590469, 17.74794969,  2.57838496,  1.97162103,  0.12613963])

In [20]:
np.cumsum(prcomp.explained_variance_ratio_*100)

array([ 77.57590469,  95.32385438,  97.90223934,  99.87386037,
       100.        ])