

---


# Clustering Movies from desctiptions using vector embeddings

---

In [3]:
from scipy.cluster.hierarchy import linkage , dendrogram
import matplotlib.pyplot as plt
from sklearn.cluster import AgglomerativeClustering,KMeans
import pandas as pd
import numpy as np
from sklearn.metrics import silhouette_score
import seaborn as sns
from tqdm import tqdm
from sklearn.preprocessing import StandardScaler
from sentence_transformers import SentenceTransformer

# Tis will not work in surprise environment

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
df = pd.read_csv('titles.csv')
df.shape

(5850, 15)

In [ ]:
df

             id  ... tmdb_score
0      ts300399  ...        NaN
1       tm84618  ...      8.179
2      tm154986  ...      7.300
3      tm127384  ...      7.811
4      tm120801  ...      7.600
...         ...  ...        ...
5845  tm1014599  ...        NaN
5846   tm898842  ...        NaN
5847  tm1059008  ...      6.300
5848  tm1035612  ...     10.000
5849   ts271048  ...     10.000

[5850 rows x 15 columns]

### Filtering Indian movies

In [ ]:
df_indian_movies = df[(df['production_countries'].str.contains('IN')) & (df['type']=='MOVIE')]
df_indian_movies

             id                 title  ... tmdb_popularity tmdb_score
19      tm94651               Dostana  ...           3.980        4.9
21     tm100027   Alibaba Aur 40 Chor  ...           2.582        6.8
25     tm356209             Singapore  ...           0.792        6.3
29     tm336403           Khoon Khoon  ...           1.948        3.8
30     tm107372            Manoranjan  ...           1.532        5.3
...         ...                   ...  ...             ...        ...
5766  tm1004011         Time to Dance  ...           1.043        4.0
5788   tm987730             Tribhanga  ...           4.294        7.0
5795   tm988613  Madam Chief Minister  ...           2.301        6.7
5821  tm1110241                Kaaval  ...           1.978        5.3
5832   tm996479  Tuesdays And Fridays  ...           1.589        5.3

[577 rows x 15 columns]

In [ ]:
model  = SentenceTransformer('BAAI/bge-small-en-v1.5')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  133MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
model.encode("I am feeling excellent").shape

(384,)

### Every embeded text will have array of 384 numbers

In [ ]:
all_desc = list(df_indian_movies['description'])
out_embs = []
for r in tqdm(all_desc):
  embd = model.encode(r)
  out_embs.append(embd)
out_embd = np.array(out_embs)

100%|██████████| 577/577 [00:42<00:00, 13.47it/s]

In [ ]:
out_embd.shape

(577, 384)

In [ ]:
df_indian_movies['movieID']= df_indian_movies['id']+'-'+df_indian_movies['title']
df_embd = pd.DataFrame(out_embs,index = list(df_indian_movies['movieID']))
df_embd

/tmp/ipykernel_1300/2353834856.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_indian_movies['movieID']= df_indian_movies['id']+'-'+df_indian_movies['title']

                                    0         1    ...       382       383
tm94651-Dostana               -0.075357  0.013868  ...  0.049413  0.022834
tm100027-Alibaba Aur 40 Chor  -0.044140  0.060243  ... -0.009698  0.019127
tm356209-Singapore             0.033862  0.030536  ... -0.041923 -0.008498
tm336403-Khoon Khoon          -0.149428  0.020323  ...  0.041777 -0.091707
tm107372-Manoranjan           -0.044192  0.066234  ...  0.001144 -0.000315
...                                 ...       ...  ...       ...       ...
tm1004011-Time to Dance       -0.060569 -0.043502  ...  0.012461 -0.044530
tm987730-Tribhanga            -0.035807  0.042290  ... -0.031457 -0.000590
tm988613-Madam Chief Minister -0.040465  0.064742  ... -0.017669 -0.006640
tm1110241-Kaaval              -0.034413  0.052420  ... -0.036518 -0.015049
tm996479-Tuesdays And Fridays  0.017332  0.064089  ...  0.005410  0.013119

[577 rows x 384 columns]

In [ ]:
from sklearn.cluster import HDBSCAN
from sklearn.metrics import silhouette_samples

In [ ]:
hdbbscan = HDBSCAN(min_cluster_size=2)
hdbbscan.fit(out_embs)
df_embd['hdbscan_cluster'] = hdbbscan.labels_
df_embd['hdbscan_cluster'].value_counts()

hdbscan_cluster
-1     413
 57     20
 40      9
 58      6
 48      5
 25      4
 36      4
 27      4
 51      3
 50      3
 15      3
 18      3
 38      3
 52      3
 21      3
 2       3
 11      2
 42      2
 35      2
 14      2
 19      2
 13      2
 43      2
 39      2
 47      2
 12      2
 29      2
 41      2
 54      2
 32      2
 34      2
 53      2
 6       2
 10      2
 20      2
 55      2
 1       2
 17      2
 46      2
 7       2
 22      2
 3       2
 49      2
 56      2
 45      2
 37      2
 28      2
 31      2
 5       2
 23      2
 4       2
 30      2
 8       2
 33      2
 26      2
 0       2
 16      2
 44      2
 9       2
 24      2
Name: count, dtype: int64

In [ ]:
df_embd[df_embd['hdbscan_cluster']==40]

                                         0         1  ...       383  hdbscan_cluster
tm358653-Ujala                   -0.049333  0.046700  ... -0.086344               40
tm36475-Kabhi Khushi Kabhie Gham -0.009770  0.098484  ... -0.032099               40
tm201365-Brothers                -0.059697  0.039701  ... -0.078360               40
tm233344-Kapoor & Sons            0.004743  0.063174  ... -0.026168               40
tm431928-Rajma Chawal             0.013039  0.035680  ... -0.003386               40
tm831061-Magamuni                -0.035730  0.052579  ... -0.082065               40
tm847212-Thambi                  -0.028092  0.020402  ... -0.078210               40
tm810873-Thottappan              -0.016061  0.024428  ... -0.027344               40
tm1036797-Sardar Ka Grandson      0.016283  0.069804  ... -0.036171               40

[9 rows x 385 columns]

In [ ]:
df_indian_movies[(df_embd['hdbscan_cluster']==48).values]

            id  ...                            movieID
434    tm61056  ...             tm61056-Dil Chahta Hai
566   tm154375  ...      tm154375-Main Aurr Mrs Khanna
721   tm182125  ...  tm182125-Zindagi Na Milegi Dobara
1455  tm233843  ...      tm233843-Pyaar Ka Punchnama 2
4248  tm946277  ...                      tm946277-Love

[5 rows x 16 columns]