In [30]:
from scipy.cluster.hierarchy import linkage,dendrogram
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans,DBSCAN,HDBSCAN
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import os 
os.chdir("E:/Machine_Learning/Datasets/")

In [28]:
df = pd.read_csv('milk.csv',index_col=0)
df

            water  protein   fat  lactose   ash
Animal
HORSE        90.1      2.6   1.0      6.9  0.35
ORANGUTAN    88.5      1.4   3.5      6.0  0.24
MONKEY       88.4      2.2   2.7      6.4  0.18
DONKEY       90.3      1.7   1.4      6.2  0.40
HIPPO        90.4      0.6   4.5      4.4  0.10
CAMEL        87.7      3.5   3.4      4.8  0.71
BISON        86.9      4.8   1.7      5.7  0.90
BUFFALO      82.1      5.9   7.9      4.7  0.78
GUINEA PIG   81.9      7.4   7.2      2.7  0.85
CAT          81.6     10.1   6.3      4.4  0.75
FOX          81.6      6.6   5.9      4.9  0.93
LLAMA        86.5      3.9   3.2      5.6  0.80
MULE         90.0      2.0   1.8      5.5  0.47
PIG          82.8      7.1   5.1      3.7  1.10
ZEBRA        86.2      3.0   4.8      5.3  0.70
SHEEP        82.0      5.6   6.4      4.7  0.91
DOG          76.3      9.3   9.5      3.0  1.20
ELEPHANT     70.7      3.6  17.6      5.6  0.63
RABBIT       71.3     12.3  13.1      1.9  2.30
RAT          72.5      9.2  12.6      3.3  1.40
DEER         65.9     10.4  19.7      2.6  1.40
REINDEER     64.8     10.7  20.3      2.5  1.40
WHALE        64.8     11.1  21.2      1.6  1.70
SEAL         46.4      9.7  42.0      0.0  0.85
DOLPHIN      44.9     10.6  34.9      0.9  0.53

In [7]:
scaler = StandardScaler()
df_scl= scaler.fit_transform(df)

In [16]:
dbs = DBSCAN(eps = 1.5,min_samples = 2)  
dbs.fit(df_scl)
dbs.labels_  # -1 indicates outliers

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       -1, -1,  0,  0,  0,  0,  1,  1])

In [24]:
len(np.unique(dbs.labels_[dbs.labels_!=-1]))

2

In [13]:
inliner_obs = df_scl[dbs.labels_!= -1]
inliner_lbls = dbs.labels_[dbs.labels_!= -1]
silhouette_score(inliner_obs,inliner_lbls)

0.5528890106341011

In [27]:
epsi = np.linspace(0.1,3,10)
min_pts = [2,3,4,5]
scores=[]
for e in epsi:
    for m in min_pts:
        dbs = DBSCAN(eps = e,min_samples=m)
        dbs.fit(df_scl)
        if len(np.unique(dbs.labels_[dbs.labels_!=-1])) >=2:
            inliner_obs = df_scl[dbs.labels_!= -1]
            inliner_lbls = dbs.labels_[dbs.labels_!= -1]
            scores.append([e,m,silhouette_score(inliner_obs,inliner_lbls)])
df_dbs = pd.DataFrame(scores,columns=['Epsilon','Min Samples','Score'])
df_dbs

    Epsilon  Min Samples     Score
0  0.422222            2  0.651894
1  0.422222            3  0.538518
2  0.744444            2  0.488035
3  0.744444            3  0.418695
4  1.066667            4  0.513335
5  1.388889            2  0.552889
6  1.711111            2  0.518685
7  2.033333            2  0.518685
8  2.355556            2  0.518685
9  2.677778            2  0.518685

-----
# HDBSCAN
-----

In [31]:
hdbs = HDBSCAN(min_cluster_size=3)  
hdbs.fit(df_scl)
hdbs.labels_

array([ 2,  2,  2,  2, -1,  3, -1,  1, -1, -1,  1,  3,  2,  1,  3,  1,  0,
       -1, -1,  0,  0,  0,  0, -1, -1])

In [32]:
inliner_obs = df_scl[hdbs.labels_!= -1]
inliner_lbls = hdbs.labels_[hdbs.labels_!= -1]
silhouette_score(inliner_obs,inliner_lbls)

0.5032777845817116