In [49]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder
from ipywidgets import interact
from ipywidgets import widgets
import os
os.chdir("E:/Machine_Learning/Datasets/")

#### df = pd.read_csv('Groceries.csv')
#### df
this code will throw error
#### read_csv file can only read lines of equal length but in dataset we dont have same number of elements in eah row 
#### so we have to do preprocessing to load the data

In [50]:
groceries = []
with open('Groceries.csv','r') as f:groceries = f.read()
groceries = groceries.split("\n")
groceries_list = []
for i in groceries:
    groceries_list.append(i.split(","))

## TransactionEncoder takes list of list as input,so we have converted data accordingly.

In [51]:
te = TransactionEncoder()
te_arr = te.fit_transform(groceries_list)
te_arr

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False],
       [False, False, False, ...,  True, False, False],
       ...,
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], shape=(9835, 169))

In [52]:
fp_df = pd.DataFrame(te_arr,columns=te.columns_)
fp_df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [53]:
item_set = apriori(fp_df , min_support=  0.05 , use_colnames=True)
item_set

     support                        itemsets
0   0.052466                          (beef)
1   0.080529                  (bottled beer)
2   0.110524                 (bottled water)
3   0.064870                   (brown bread)
4   0.055414                        (butter)
5   0.077682                   (canned beer)
6   0.082766                  (citrus fruit)
7   0.058058                        (coffee)
8   0.053279                          (curd)
9   0.063447                 (domestic eggs)
10  0.058973                   (frankfurter)
11  0.072293         (fruit/vegetable juice)
12  0.058566                     (margarine)
13  0.052364                       (napkins)
14  0.079817                    (newspapers)
15  0.193493              (other vegetables)
16  0.088968                        (pastry)
17  0.075648                     (pip fruit)
18  0.057651                          (pork)
19  0.183935                    (rolls/buns)
20  0.108998               (root vegetables)
21  0.093950                       (sausage)
22  0.098526                 (shopping bags)
23  0.174377                          (soda)
24  0.104931                (tropical fruit)
25  0.071683            (whipped/sour cream)
26  0.255516                    (whole milk)
27  0.139502                        (yogurt)
28  0.074835  (whole milk, other vegetables)
29  0.056634        (whole milk, rolls/buns)
30  0.056024            (whole milk, yogurt)

In [54]:
rules = association_rules(item_set,metric = 'confidence',min_threshold = 0.2)
rules = rules[['antecedents','consequents','support','confidence','lift']]
rules.sort_values(by =['support','confidence','lift'],ascending = False)

          antecedents         consequents   support  confidence      lift
1  (other vegetables)        (whole milk)  0.074835    0.386758  1.513634
0        (whole milk)  (other vegetables)  0.074835    0.292877  1.513634
3        (rolls/buns)        (whole milk)  0.056634    0.307905  1.205032
2        (whole milk)        (rolls/buns)  0.056634    0.221647  1.205032
5            (yogurt)        (whole milk)  0.056024    0.401603  1.571735
4        (whole milk)            (yogurt)  0.056024    0.219260  1.571735

# Same process on 'DatasetA.csv'

In [55]:
groceries = []
with open('DataSetA.csv','r') as f:groceries = f.read()
groceries = groceries.split("\n")
groceries_list = []
for i in groceries:
    groceries_list.append(i.split(","))

In [56]:
te = TransactionEncoder()
te_arr = te.fit_transform(groceries_list)
fp_df = pd.DataFrame(te_arr,columns=te.columns_)
fp_df

,,Bread,Butter,Cheese,Coffee Powder,Ghee,Lassi,Milk,Panner,Sugar,Sweet,Tea Powder,Yougurt
0,True,False,True,True,True,True,True,False,False,False,False,False,True
1,True,False,False,False,True,True,False,False,False,False,False,False,False
2,True,False,True,True,False,False,True,False,False,False,False,True,False
3,True,True,True,True,True,False,False,False,True,False,False,True,False
4,True,False,True,True,True,False,False,False,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12522,True,True,False,True,True,False,False,False,False,True,False,False,False
12523,True,True,False,True,False,False,False,True,False,False,False,False,True
12524,True,True,False,True,False,True,False,False,False,True,False,False,True
12525,True,True,False,False,False,False,False,False,True,False,False,False,True
12526,True,False,False,False,False,False,False,False,False,False,False,False,False

### This dataset have traiiling comma at the end of every row thats why we are getting an extra column at first index as empty string ('') and we have to remove that

In [57]:
fp_df = fp_df.iloc[:,1:]
fp_df.head()

,Bread,Butter,Cheese,Coffee Powder,Ghee,Lassi,Milk,Panner,Sugar,Sweet,Tea Powder,Yougurt
0,False,True,True,True,True,True,False,False,False,False,False,True
1,False,False,False,True,True,False,False,False,False,False,False,False
2,False,True,True,False,False,True,False,False,False,False,True,False
3,True,True,True,True,False,False,False,True,False,False,True,False
4,False,True,True,True,False,False,False,False,True,True,False,True

In [62]:
item_set = apriori(fp_df , min_support=  0.1 , use_colnames=True)
item_set

     support                itemsets
0   0.437774                 (Bread)
1   0.437535                (Butter)
2   0.437136                (Cheese)
3   0.439770         (Coffee Powder)
4   0.439850                  (Ghee)
..       ...                     ...
74  0.201884        (Yougurt, Sugar)
75  0.199808     (Sweet, Tea Powder)
76  0.197813        (Sweet, Yougurt)
77  0.198451   (Yougurt, Tea Powder)
78  0.100982  (Sweet, Panner, Lassi)

[79 rows x 2 columns]

In [63]:
rules = association_rules(item_set,metric = 'confidence',min_threshold = 0.5)
rules = rules[['antecedents','consequents','support','confidence','lift']]
rules.sort_values(by =['support','confidence','lift'],ascending = False)

       antecedents consequents   support  confidence      lift
1  (Lassi, Panner)     (Sweet)  0.100982    0.506608  1.157446
0  (Sweet, Panner)     (Lassi)  0.100982    0.504990  1.164582

In [65]:
relevant_rules = rules[rules['lift']>1]
relevant_rules.sort_values(by = ['confidence','lift','support'],ascending=False)

       antecedents consequents   support  confidence      lift
1  (Lassi, Panner)     (Sweet)  0.100982    0.506608  1.157446
0  (Sweet, Panner)     (Lassi)  0.100982    0.504990  1.164582