In [1]:
from scipy.cluster.hierarchy import linkage,dendrogram
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import os 
os.chdir("E:/Machine_Learning/Datasets/")

In [2]:
milk = pd.read_csv('milk.csv',index_col=0)
milk.head()

           water  protein  fat  lactose   ash
Animal
HORSE       90.1      2.6  1.0      6.9  0.35
ORANGUTAN   88.5      1.4  3.5      6.0  0.24
MONKEY      88.4      2.2  2.7      6.4  0.18
DONKEY      90.3      1.7  1.4      6.2  0.40
HIPPO       90.4      0.6  4.5      4.4  0.10

In [3]:
clf = IsolationForest(contamination=0.05,random_state=26)
clf.fit(milk)
predictions = clf.predict(milk)
print("percentage of outliers = "+str((predictions<0).mean()*100)+"%")
ab_ind = np.where(predictions<0)
print('Outliers : ')
print(ab_ind)

percentage of outliers = 8.0%
Outliers :
(array([23, 24]),)

In [4]:
milk.index[ab_ind]

Index(['SEAL', 'DOLPHIN'], dtype='object', name='Animal')

## Same for nutrient dataset

In [5]:
nu = pd.read_csv('nutrient.csv',index_col=0)
nu.head()

              energy  protein  fat  calcium  iron
Food_Item
BEEF BRAISED     340       20   28        9   2.6
HAMBURGER        245       21   17        9   2.7
BEEF ROAST       420       15   39        7   2.0
BEEF STEAK       375       19   32        9   2.6
BEEF CANNED      180       22   10       17   3.7

In [6]:
clf = IsolationForest(contamination=0.05,random_state=26)
clf.fit(nu)
predictions = clf.predict(nu)
print("percentage of outliers = "+str((predictions<0).mean()*100)+"%")
ab_ind = np.where(predictions<0)
print('Outliers : ')
print(ab_ind)

percentage of outliers = 7.4074074074074066%
Outliers :
(array([ 2, 17]),)

In [7]:
nu.index[ab_ind]

Index(['BEEF ROAST', 'CLAMS CANNED'], dtype='object', name='Food_Item')