In [49]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
import os
os.chdir('E:/Machine_Learning/Cases/Vehicle Silhouettes')

In [50]:
vehicle = pd.read_csv('Vehicle.csv')
vehicle.head()

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus

In [51]:
X,y = vehicle.drop('Class',axis=1) , vehicle['Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [52]:
ks = np.arange(1,16)
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,y_train)
    y_pred = knn.predict(X_test)
    acc = accuracy_score(y_test,y_pred)
    scores.append([k,acc])
df_scores = pd.DataFrame(scores,columns=['k','Accuracy Score'])
df_scores.nlargest(1,'Accuracy Score')

   k  Accuracy Score
0  1        0.677165

In [53]:
X,y = vehicle.drop('Class',axis=1) , vehicle['Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)

#### Without using stratify the data can be splitted in some different proportion

In [54]:
y.value_counts(normalize=True)  # normalize=True gives the porportional values to total count ie(value_count/total count)

Class
bus     0.257683
saab    0.256501
opel    0.250591
van     0.235225
Name: proportion, dtype: float64

In [55]:
y_test.value_counts(normalize=True)

Class
saab    0.267717
opel    0.255906
bus     0.244094
van     0.232283
Name: proportion, dtype: float64

## Using stratify=y

In [56]:
X,y = vehicle.drop('Class',axis=1) , vehicle['Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26, stratify =vehicle['Class'])  # stratify=y

In [57]:
y.value_counts(normalize=True)*100

Class
bus     25.768322
saab    25.650118
opel    25.059102
van     23.522459
Name: proportion, dtype: float64

In [58]:
y_test.value_counts(normalize=True)*100

Class
saab    25.590551
bus     25.590551
opel    25.196850
van     23.622047
Name: proportion, dtype: float64

In [59]:
vehicle = pd.read_csv('Vehicle.csv')
vehicle.head()

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus

-----
#### In this dataset there are many different values for columns some columns has values in single digit and  some has near 500-900 but this creates the problem while finding the distance,... because the lower value features are ignored when there are higher value columns 

#### for example when we are taking 'Sc.Var.maxis' this column and 'Skew.maxis' this column the smaller value doesn't nake that much difference in eucledian distance but the larger value ('Sc.Var.maxis') this will have more impact on the eucledian distance .... so thats why we have to use standard scaling

-----

### Thats why the scaling is very important in KNN 
### Using StandardScaler

In [60]:
X , y = vehicle.drop('Class',axis=1) , vehicle['Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [61]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [62]:
ks = np.arange(1,16)
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled,y_train)
    y_pred = knn.predict(X_test_scaled)
    acc = accuracy_score(y_test,y_pred)
    scores.append([k,acc])
df_scores = pd.DataFrame(scores,columns=['k','Accuracy Score'])
df_scores.nlargest(1,'Accuracy Score')

   k  Accuracy Score
2  3        0.728346

## Pipeline

In [63]:
scaler = StandardScaler().set_output(transform='pandas')
ks = np.arange(1,16)
scores = []
for n in ks:
    knn = KNeighborsClassifier(n_neighbors=n)
    pipe = Pipeline([('SC',scaler),('KNN',knn)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append([n,accuracy_score(y_test,y_pred)])

df_scores = pd.DataFrame(scores,columns=['K','Accuracy Score'])
df_scores.nlargest(1,'Accuracy Score')

   K  Accuracy Score
2  3        0.728346

### Using Min-Max Scaler

In [64]:
mx = MinMaxScaler().set_output(transform='pandas')
ks = np.arange(1,16)
scores = []
for n in ks:
    knn = KNeighborsClassifier(n_neighbors=n)
    pipe = Pipeline([('MinMax',mx),('KNN',knn)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append([n,accuracy_score(y_test,y_pred)])

df_scores = pd.DataFrame(scores,columns=['K','Accuracy Score'])
df_scores.nlargest(1,'Accuracy Score')

   K  Accuracy Score
5  6         0.73622