In [6]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler,OneHotEncoder
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
import os
os.chdir('E:/Machine_Learning/Cases/human-resources-analytics')

In [3]:
df = pd.read_csv('HR_comma_sep.csv')
df.head()

   satisfaction_level  last_evaluation  number_project  ...  promotion_last_5years  Department  salary
0                0.38             0.53               2  ...                      0       sales     low
1                0.80             0.86               5  ...                      0       sales  medium
2                0.10             0.77               6  ...                      0       sales     low
3                0.92             0.85               5  ...                      0       sales     low
4                0.89             1.00               5  ...                      0       sales     low

[5 rows x 10 columns]

In [4]:
X , y = df.drop('left',axis =1), df['left']

In [42]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

ohe = OneHotEncoder(sparse_output= True,drop='first')
ct = make_column_transformer((ohe,make_column_selector(dtype_include='object')),
                            ('passthrough',make_column_selector(dtype_include=['int64','float64'])),
                            verbose_feature_names_out=False)
scaler = StandardScaler()

In [43]:
ks = np.arange(1,16)
scores = []
for k in ks :
    knn = KNeighborsClassifier(n_neighbors=k)
    pipe = Pipeline([('OHE',ct),('SCL',scaler),('KNN',knn)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    acc = accuracy_score(y_test,y_pred)
    scores.append([k,acc])
print(scores)

[[np.int64(1), 0.9644365414536563], [np.int64(2), 0.960213380751278], [np.int64(3), 0.9482107134918871], [np.int64(4), 0.9464325405645699], [np.int64(5), 0.941320293398533], [np.int64(6), 0.945098910869082], [np.int64(7), 0.9408757501667037], [np.int64(8), 0.9415425650144477], [np.int64(9), 0.9368748610802401], [np.int64(10), 0.9377639475438987], [np.int64(11), 0.9339853300733496], [np.int64(12), 0.9344298733051789], [np.int64(13), 0.9302067126028006], [np.int64(14), 0.9322071571460324], [np.int64(15), 0.9290953545232273]]

In [44]:
abcd=pd.DataFrame(scores,columns=['k','Accuracy Score'])
abcd.nlargest(1,'Accuracy Score')

   k  Accuracy Score
0  1        0.964437