In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score
import seaborn as sns
os.chdir("E:/Machine_Learning/Datasets")

In [4]:
housing  = pd.read_csv('Housing.csv')
dum_hous = pd.get_dummies(housing,drop_first=True)
X , y = dum_hous.drop('price',axis = 1) , dum_hous['price']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
r2_score(y_test,y_pred)

0.6791781818067918

In [42]:
housing.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [53]:
dum_hous

,price,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,42000.0,5850,3,1,2,1,True,False,True,False,False,False
1,38500.0,4000,2,1,1,0,True,False,False,False,False,False
2,49500.0,3060,3,1,1,0,True,False,False,False,False,False
3,60500.0,6650,3,1,2,0,True,True,False,False,False,False
4,61000.0,6360,2,1,1,0,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,0,True,True,False,False,True,False
542,94000.0,6000,3,2,4,0,True,False,False,False,True,False
543,103000.0,6000,3,2,4,1,True,True,False,False,True,False
544,105000.0,6000,3,2,2,1,True,True,False,False,True,False
545,105000.0,6000,3,1,2,1,True,False,False,False,True,False

In [26]:
tst = pd.read_csv('tst_Housing.csv')
tst

,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,5600,3,1,2,yes,no,yes,no,no,1,no
1,4355,2,1,1,yes,no,no,no,no,0,no
2,3412,3,1,1,yes,no,no,no,no,0,no
3,6666,2,2,2,yes,yes,no,no,no,0,no

In [41]:
dum_tst_hous = pd.get_dummies(tst)
dum_tst_hous

,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_no,recroom_yes,fullbase_no,fullbase_yes,gashw_no,airco_no,prefarea_no
0,5600,3,1,2,1,True,True,False,False,True,True,True,True
1,4355,2,1,1,0,True,True,False,True,False,True,True,True
2,3412,3,1,1,0,True,True,False,True,False,True,True,True
3,6666,2,2,2,0,True,False,True,True,False,True,True,True

In [35]:
cate = list(tst.columns[tst.dtypes == 'str'])

In [37]:
ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')
ohe.fit_transform(tst[cate])

,driveway_yes,recroom_no,recroom_yes,fullbase_no,fullbase_yes,gashw_no,airco_no,prefarea_no
0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
1,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0
2,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0
3,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0

## Therefore the get_dummies fails here

In [54]:
housing  = pd.read_csv('Housing.csv')
housing.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [63]:
X , y = housing.drop('price',axis = 1) , housing['price']

ohe = OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')

ct = make_column_transformer((ohe,make_column_selector(dtype_include='object')),
                            ('passthrough',make_column_selector(dtype_include=['int64','float64'])),
                            verbose_feature_names_out=False)

ct = ct.set_output(transform='pandas')
X_ohe = ct.fit_transform(X)
X_ohe.head()

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,lotsize,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,5850,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,4000,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,3060,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,6650,3,1,2,0
4,1.0,0.0,0.0,0.0,0.0,0.0,6360,2,1,1,0

In [48]:
X_train,X_test,y_train,y_test = train_test_split(X_ohe,y,test_size=0.3,random_state=26)
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
r2_score(y_test,y_pred)

0.6791781818067812

### Now we use same "ct" object for transforming the values in tst_housing dataset
### This is called Inferencing

In [65]:
tst = pd.read_csv('tst_Housing.csv')
tst

,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,5600,3,1,2,yes,no,yes,no,no,1,no
1,4355,2,1,1,yes,no,no,no,no,0,no
2,3412,3,1,1,yes,no,no,no,no,0,no
3,6666,2,2,2,yes,yes,no,no,no,0,no

In [66]:
ct.transform(tst)    
#  here we have only used transform on the dataset (because here whole dataset is our X ie. features)
#

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,lotsize,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,5600,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,4355,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,3412,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,6666,2,2,2,0

In [67]:
lr.predict(testing)

array([66460.25330163, 42714.87464687, 40469.90014429, 75958.60712357])

In [68]:
ct.fit_transform(tst)

   recroom_yes  fullbase_yes  lotsize  bedrooms  bathrms  stories  garagepl
0          0.0           1.0     5600         3        1        2         1
1          0.0           0.0     4355         2        1        1         0
2          0.0           0.0     3412         3        1        1         0
3          1.0           0.0     6666         2        2        2         0

### Using fit() and transform() and fit_transform()

In [71]:
housing  = pd.read_csv('Housing.csv')
X , y = housing.drop('price',axis = 1) , housing['price']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)

In [73]:
ohe = OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')

ct = make_column_transformer((ohe,make_column_selector(dtype_include='object')),
                            ('passthrough',make_column_selector(dtype_include=['int64','float64'])),
                            verbose_feature_names_out=False)

ct = ct.set_output(transform='pandas')

X_train_transformed = ct.fit_transform(X_train)

In [75]:
X_test_transformed = ct.transform(X_test) # use only transform() on testing data

In [76]:
lr = LinearRegression()
lr.fit(X_train_transformed,y_train)
y_pred = lr.predict(X_test_transformed)

In [77]:
r2_score(y_test,y_pred)

0.6791781818067812