In [16]:
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,r2_score
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder,MinMaxScaler
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.neighbors import KNeighborsRegressor
os.chdir("E:/Machine_Learning/Datasets")

In [2]:
df = pd.read_csv('Housing.csv')
df.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [5]:
X , y = df.drop('price',axis=1),df['price']

In [9]:
ohe = OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')

ct = make_column_transformer((ohe,make_column_selector(dtype_include='object')),
                                ('passthrough',make_column_selector(dtype_include=['int64','float64'])),
                                verbose_feature_names_out=False).set_output(transform='pandas')

In [13]:
scaler = StandardScaler()

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)

ks = np.arange(1,16)
scores = []
for k in ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    pipe = Pipeline([("OHE",ct),('SCL',scaler),('KNN',knn)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    r2 = r2_score(y_test,y_pred)
    scores.append([k,r2])

In [15]:
df_r2 = pd.DataFrame(scores,columns=['k','r2'])
df_r2.nlargest(1,'r2')

    k        r2
9  10  0.704812

In [18]:
scaler = MinMaxScaler()

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)

ks = np.arange(1,16)
scores = []
for k in ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    pipe = Pipeline([("OHE",ct),('SCL',scaler),('KNN',knn)])
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    r2 = r2_score(y_test,y_pred)
    scores.append([k,r2])
df_r2 = pd.DataFrame(scores,columns=['k','r2'])
df_r2.nlargest(1,'r2')

   k        r2
3  4  0.648484