In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import root_mean_squared_error,r2_score
import seaborn as sns
os.chdir("E:/Machine_Learning/Datasets")

In [2]:
salary = pd.read_csv('Exp_Salaries.csv')
salary.head()

,Salary,Years_Previous_Experience,Years Employed,Years_Education,Gender,Department,Number_Supervised
0,32782,1,0,7,Male,A,0
1,32920,3,15,9,Female,A,4
2,29548,6,5,1,Male,A,0
3,39828,6,18,5,Female,A,5
4,31528,11,3,3,Male,A,6

In [3]:
X ,y=salary.drop('Salary',axis=1) , salary['Salary']

In [10]:
ohe = OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')
ct = make_column_transformer((ohe,make_column_selector(dtype_include='object')),
                            ('passthrough',make_column_selector(dtype_include=['int64','float64'])),
                            verbose_feature_names_out=False)
ct = ct.set_output(transform='pandas')
X_ohe = ct.fit_transform(X)
X_ohe.head()

,Gender_Male,Department_B,Department_C,Department_D,Years_Previous_Experience,Years Employed,Years_Education,Number_Supervised
0,1.0,0.0,0.0,0.0,1,0,7,0
1,0.0,0.0,0.0,0.0,3,15,9,4
2,1.0,0.0,0.0,0.0,6,5,1,0
3,0.0,0.0,0.0,0.0,6,18,5,5
4,1.0,0.0,0.0,0.0,11,3,3,6