In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import os
os.chdir("E:/Machine_Learning/Datasets")

In [6]:
milk = pd.read_csv('milk.csv',index_col=0)
milk.head()

           water  protein  fat  lactose   ash
Animal
HORSE       90.1      2.6  1.0      6.9  0.35
ORANGUTAN   88.5      1.4  3.5      6.0  0.24
MONKEY      88.4      2.2  2.7      6.4  0.18
DONKEY      90.3      1.7  1.4      6.2  0.40
HIPPO       90.4      0.6  4.5      4.4  0.10

In [7]:
scaler = StandardScaler().set_output(transform='pandas')
scaler.fit(milk) # calculates the mean and SD's for all the columns
print('Colums Means : ',scaler.mean_)
print("Column SD's : ",scaler.scale_)

Colums Means :  [78.184   6.212  10.308   4.132   0.8632]
Column SD's :  [12.55893881  3.57875062 10.30549058  1.79481921  0.49462487]

In [9]:
milk.describe() # in this the values of SD's may be different because it has coefficient as (n-1)

           water    protein        fat   lactose        ash
count  25.000000  25.000000  25.000000  25.00000  25.000000
mean   78.184000   6.212000  10.308000   4.13200   0.863200
std    12.817913   3.652547  10.517997   1.83183   0.504824
min    44.900000   0.600000   1.000000   0.00000   0.100000
25%    71.300000   3.000000   3.400000   2.70000   0.530000
50%    82.000000   5.900000   6.300000   4.70000   0.800000
75%    87.700000   9.700000  13.100000   5.60000   1.100000
max    90.400000  12.300000  42.000000   6.90000   2.300000

In [11]:
scaler.transform(milk) # transform the value accordingly (Standard Scaling)  xi = (xi-meu)/SD

               water   protein       fat   lactose       ash
Animal
HORSE       0.948806 -1.009291 -0.903208  1.542217 -1.037554
ORANGUTAN   0.821407 -1.344603 -0.660619  1.040773 -1.259945
MONKEY      0.813445 -1.121062 -0.738247  1.263637 -1.381249
DONKEY      0.964731 -1.260775 -0.864394  1.152205 -0.936467
HIPPO       0.972694 -1.568145 -0.563583  0.149319 -1.542988
CAMEL       0.757707 -0.757806 -0.670322  0.372182 -0.309730
BISON       0.694008 -0.394551 -0.835283  0.873626  0.074400
BUFFALO     0.311810 -0.087181 -0.233662  0.316466 -0.168208
GUINEA PIG  0.295885  0.331959 -0.301587 -0.797852 -0.026687
CAT         0.271998  1.086413 -0.388919  0.149319 -0.228860
FOX         0.271998  0.108418 -0.427733  0.427898  0.135052
LLAMA       0.662158 -0.646036 -0.689729  0.817910 -0.127774
MULE        0.940844 -1.176947 -0.825579  0.762194 -0.794946
PIG         0.367547  0.248131 -0.505362 -0.240693  0.478747
ZEBRA       0.638270 -0.897520 -0.534472  0.650762 -0.329947
SHEEP       0.303847 -0.171009 -0.379215  0.316466  0.094617
DOG        -0.150013  0.862871 -0.078405 -0.630704  0.680920
ELEPHANT   -0.595910 -0.729864  0.707584  0.817910 -0.471468
RABBIT     -0.548135  1.701152  0.270924 -1.243579  2.904828
RAT        -0.452586  0.834928  0.222406 -0.463556  1.085267
DEER       -0.978108  1.170241  0.911359 -0.853568  1.085267
REINDEER   -1.065695  1.254069  0.969580 -0.909284  1.085267
WHALE      -1.065695  1.365840  1.056912 -1.410727  1.691787
SEAL       -2.530787  0.974642  3.075254 -2.302182 -0.026687
DOLPHIN    -2.650224  1.226126  2.386301 -1.800738 -0.673642

### the scaling is very important in KNN